### PR TITLE
Route using complete toolname

### LINKED ISSUE #449: Including an MCPServer with no prefix causes incorrect routing and undeterministic behaviour
When an MCPServer has no tool prefix, there is undeterministic behaviour.
This is due to how the server matching for a tool name is looked up when a tool call happens.
There are 2 places where this happens, in https://github.com/kagenti/mcp-gateway/blob/8665eaaa9ba666a961e0d9424c8549d1356ecf30/internal/mcp-router/request_handlers.go#L192 and https://github.com/kagenti/mcp-gateway/blob/8665eaaa9ba666a961e0d9424c8549d1356ecf30/internal/mcp-router/request_handlers.go#L226.
As the servers are iterated through, if a match is found on the tool prefix, that server is used for routing.
However, if there is no prefix defined for a server (i.e. an empty string), it will match every tool name.
So if that server is the first in the iteration, it will always match.
If the non prefix server is last in the iteration, then the behaviour is as expected.
If the non prefix server is somewhere in the middle of the iteration, some tools may get routed correctly, and some may not.

A simple fix for this would be to treat a non prefix server differently, and always have it be the last server to check, if no other prefix match was found.

NOTE: This is different from (but related to) the known problem where currently you can't have more than 1 MCPServer without a tool prefix due to matching on the first server.
See related proposal and discussion in #434 for additional context and a proposal for how this feature should behave.

### PR DESCRIPTION
**Pull request by esnible**
Resolves #449 

This PR causes the router to take advantage of the complete name of the tool when looking up the upstream.

This PR is based on @maleck13 's PR, rather than _main_.

cc @david-martin

### CODE REVIEW

File: internal/broker/broker.go [hunk 1]
```diff
@@ -222,6 +226,25 @@ func (m *mcpBrokerImpl) ToolAnnotations(serverID config.UpstreamMCPID, tool stri
...
+			slog.Info("[EXT-PROC] Found matching server",
+				"toolName", tool,
+				"serverPrefix", upstream.MCP.GetPrefix(),
+				"serverName", upstream.MCP.GetName())
+			retval := upstream.MCP.GetConfig()
+			return &retval
+		}
+	}
+
+	slog.Info("Tool name doesn't match any configured server prefix", "tool", tool)
```
Comment (maleck13) [inline internal/broker/broker.go]:
```suggestion
	slog.Info("Tool name doesn't match any configured server", "tool", tool, "prefix",upstream.MCP.GetPrefix())
```

File: internal/mcp-router/request_handlers.go [hunk 2]
```diff
@@ -189,36 +189,34 @@ func (s *ExtProcServer) HandleToolCall(ctx context.Context, mcpReq *MCPRequest)
 		calculatedResponse.WithImmediateResponse(404, "session no longer valid")
 		return calculatedResponse.Build()
 	}
-	serverInfo := s.RoutingConfig.GetServerInfo(toolName)
-	if serverInfo == nil {
-		s.Logger.Info("Tool name doesn't match any configured server prefix", "tool", toolName)
-		calculatedResponse.WithImmediateResponse(404, "not found")
-		return calculatedResponse.Build()
+
+	if s.Broker == nil {
```
Comment (maleck13) [inline internal/mcp-router/request_handlers.go]: I think we can move this in to main under setUpRouter

File: internal/mcp-router/request_handlers.go [hunk 3]
```diff
@@ -189,36 +189,34 @@ func (s *ExtProcServer) HandleToolCall(ctx context.Context, mcpReq *MCPRequest)
...
-			var parts []string
-			push := func(key string, val *bool) {
-				if val == nil {
-					parts = append(parts, fmt.Sprintf("%s=unspecified", key))
-				} else if *val {
-					parts = append(parts, fmt.Sprintf("%s=true", key))
-				} else {
-					parts = append(parts, fmt.Sprintf("%s=false", key))
-				}
+	serverInfo := s.Broker.GetServerInfo(toolName)
```
Comment (maleck13) [inline internal/mcp-router/request_handlers.go]: are we missing a nil check here? Consider having GetServerInfo return an error with some useful context that we can then log?

**Review by maleck13 — COMMENTED** [review]
some small changes and checks suggested. Also it would be good to expand the e2e coverage to cover MCPServers created with no prefix along side MCPServers created with a prefix that share tool names.

File: tests/e2e/commons.go [hunk 4]
```diff
@@ -348,8 +348,13 @@ type MCPServerRegistrationBuilder struct {
 
 // NewMCPServerRegistration creates a new registration builder with defaults
 func NewMCPServerRegistration(testName string, k8sClient client.Client) *MCPServerRegistrationBuilder {
+	return NewMCPServerRegistrationEx(testName, "e2e-server2.mcp.local", "mcp-test-server2", 9090, k8sClient)
+}
+
+// NewMCPServerRegistration creates a new registration builder with defaults
+func NewMCPServerRegistrationEx(testName, hostName, serviceName string, port int32, k8sClient client.Client) *MCPServerRegistrationBuilder {
```
Comment (maleck13) [inline tests/e2e/commons.go]: lets rename this to `NewMCPServerRegistration` and the old one to `NewMCPServerRegistrationWithDefaults`

File: tests/e2e/happy_path_test.go [hunk 5]
```diff
@@ -709,4 +709,65 @@ var _ = Describe("MCP Gateway Registration Happy Path", func() {
...
+		Eventually(func(g Gomega) {
+			toolsList, err := mcpGatewayClient.ListTools(ctx, mcp.ListToolsRequest{})
+			g.Expect(err).Error().NotTo(HaveOccurred())
+			g.Expect(toolsList).NotTo(BeNil())
+			g.Expect(verifyMCPServerToolPresent("echo", toolsList)).To(BeTrueBecause("%q should exist", "greet"))
+			g.Expect(verifyMCPServerToolPresent("hello_world", toolsList)).To(BeTrueBecause("%q should exist", "hello_world"))
+		}, TestTimeoutLong, TestRetryInterval).To(Succeed())
+
+		toolName := "hello_world"
+		GinkgoWriter.Println("tool", toolName)
```
Comment (maleck13) [inline tests/e2e/happy_path_test.go]: Not sure this is adding anything?

File: internal/mcp-router/request_handlers.go [hunk 6]
```diff
@@ -189,36 +189,34 @@ func (s *ExtProcServer) HandleToolCall(ctx context.Context, mcpReq *MCPRequest)
...
-				if val == nil {
-					parts = append(parts, fmt.Sprintf("%s=unspecified", key))
-				} else if *val {
-					parts = append(parts, fmt.Sprintf("%s=true", key))
-				} else {
-					parts = append(parts, fmt.Sprintf("%s=false", key))
-				}
+	serverInfo, err := s.Broker.GetServerInfo(toolName)
+	if err != nil {
+		s.Logger.Debug("no server for tool", "toolName", toolName)
```
[the remark this answers is not in the document]
Comment (esnible) [reply internal/mcp-router/request_handlers.go]: After reading https://modelcontextprotocol.io/specification/2025-06-18/server/tools#error-handling I have revised this code to return 200 and a JSON-RPC status code.
